version: '3'
services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm_server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: "osrm-routed --algorithm mld /data/gcc-states-latest.osrm"